language: node_js
sudo: required
node_js:
- '8'
addons:
  chrome: stable
install:
- npm install
- npm install -g codecov
before_script:
- npm install -g polymer-cli@1.7.2
script:
- xvfb-run npm test
- codecov
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "okvvBK6SL6aL7MnFxpNR+9TkM+WyfiJn/Eaq+UzVSy9TjlcK0oSK1xAdxyl7MnAHb4vsceiI0FjEhRNFrx2+/z9+bFHNLQmLLCzQMzJ8MJxZexmXWwCYRBGufjQFvR4DiOow9c+DHIgEv4eaA4dHHvbe0KzKv61iedyvUQkKELA5L6Ab5rpLSDIwXyhsEiA4QLFdhR646K4FbSzWVeQpV69in0/ilWNTd1hN/2vqmzU06a7x/ajc7irLTVD3JAgJpfSesECUQP306zW8Jd1TNVq4rmHkBmgZeqHhXQvOCNp8bRDvC8aId8a9UUqFNTkx5wStQ3zooBZTAIGYzZSd43T9lLh4pKlAvsaVqzwgfBIzsSdTJAtcpa1EAdHDao5JPWBwa/cPODsWdzB3lNIgNvfImNLyhvHqs+Qf2O2XMyJmAFoqnREmHWCZYq1FJCbpmD+RjrJn42hqrP/YcqWTfwvvfB3RO+yW/rD9bqf6OCMmA/KUL06fbAQvp5yB+tjMP8hnBNNeExLdRivvhTfP2+AgJJXKNu4FzI02Fzy56rW7WO7pARnNkwwfV1z823Lh0uLotILG/20B0TK0iRxmbovCpiRSpNir+rpiWEyzDPKg8wDwY3SMc+UpkmcGsrOAHR4Y/yDQu0vl6d5+Q/9muQks/vt+QX2TFuXGPKaShqM="
  project: "color-your-code"
env:
  global:
  - secure: SR0jKUvMTGu+oN7Mi996OKX/V811J9Emb88Svh/EJ+abB2WPuQfTcl2t4+gnqBO3Uo/C72S+VA1XFJ6bFUwiWUHfQVM9z6PREw6bg/cCKHxEh+TC7fRl5KDYdxOEuPSqjnrm1VRX9u7Wu2P1O1i+UsB23UbxMyIu3DeOuqOnZ2QMvTL5h2hDbKQMVawcZwmlT01O6fNI8hF82yLQWJSzoiqlZjcCxQ5UTo7NJYQVnnhC5fcMXJu4gIGcWKowMaLKkwfIF6WSpcPUUXtdc3htUunRxD4zVHQp4gw3Zrh9FWadBWCWoaceZNIE+Kt75vC15Gdl6RyN8PiixbyrWxgvBwKcv1eme4VNbMhKiDqiO3hQJwHup73Ld9jmS2J5LqxeHYU+9i6lUQ2HhrbSVX5P84X0E+ctrm3pbanjvfKoK6NLLQX2+w2F8gmVYwBeC9QF/dmuYF04RJTYHx9lLIDSMnhmWyD/sp62jZy+0e2mB2/jxFu+0f+iSQdfpIrnFPpRXf7rNKnv1SPIHbcKd9ctcnPJ7rXJ4/CBqga4fM5UQm6Tovo2b7pzO2RLI10xGCYpOSy7l0E6P4hKOSeyvLzXw7Lrd4qYFPzseG3XN3tWUDRVq/n5nNpQlgFOQpqi4cUHODKrMF8auYJN3md6fDxezsjDpX18V6xZqBk4efAImDc=
  - secure: okvvBK6SL6aL7MnFxpNR+9TkM+WyfiJn/Eaq+UzVSy9TjlcK0oSK1xAdxyl7MnAHb4vsceiI0FjEhRNFrx2+/z9+bFHNLQmLLCzQMzJ8MJxZexmXWwCYRBGufjQFvR4DiOow9c+DHIgEv4eaA4dHHvbe0KzKv61iedyvUQkKELA5L6Ab5rpLSDIwXyhsEiA4QLFdhR646K4FbSzWVeQpV69in0/ilWNTd1hN/2vqmzU06a7x/ajc7irLTVD3JAgJpfSesECUQP306zW8Jd1TNVq4rmHkBmgZeqHhXQvOCNp8bRDvC8aId8a9UUqFNTkx5wStQ3zooBZTAIGYzZSd43T9lLh4pKlAvsaVqzwgfBIzsSdTJAtcpa1EAdHDao5JPWBwa/cPODsWdzB3lNIgNvfImNLyhvHqs+Qf2O2XMyJmAFoqnREmHWCZYq1FJCbpmD+RjrJn42hqrP/YcqWTfwvvfB3RO+yW/rD9bqf6OCMmA/KUL06fbAQvp5yB+tjMP8hnBNNeExLdRivvhTfP2+AgJJXKNu4FzI02Fzy56rW7WO7pARnNkwwfV1z823Lh0uLotILG/20B0TK0iRxmbovCpiRSpNir+rpiWEyzDPKg8wDwY3SMc+UpkmcGsrOAHR4Y/yDQu0vl6d5+Q/9muQks/vt+QX2TFuXGPKaShqM=
