version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run:
          name: build-deploy
          command: |
          npm install
          npm install -g codecov
          npm install -g polymer-cli@1.7.2
          xvfb-run npm test
          codecov
          npm run build
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: release/1.0.0
