version: 2
jobs:
  deploy:
    steps:
      - checkout
      - run:
          name: build-deploy
          command: npm run deploy
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            only: release/1.0.0
