version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run:
          name: install-deps
          command: npm install
      - run:
          name: install-polymer
          command: sudo npm install -g polymer-cli@1.7.2
      - run:
          name: build-deploy
          command: npm run deploy
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: release/1.0.0
